# Generated by Django 4.0.6 on 2022-08-08 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0007_trabajador_fechanacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='edadTra',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
