# Generated by Django 4.0.6 on 2022-08-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0008_trabajador_edadtra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='edadTra',
            field=models.IntegerField(max_length=200),
        ),
    ]
