# Generated by Django 4.0.6 on 2022-08-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0010_alter_trabajador_edadtra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='cedula',
            field=models.IntegerField(),
        ),
    ]
