# Generated by Django 4.0.6 on 2022-08-08 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0011_alter_trabajador_cedula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='edadTra',
        ),
    ]
